"""device_family

Revision ID: 7c8b0c5db769
Revises: 993e78ec5f36
Create Date: 2026-09-23 11:08:39.273485

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '7c8b0c5db769'
down_revision: Union[str, Sequence[str], None] = '993e78ec5f36'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('devices', sa.Column('device_family', sa.String(length=32), server_default='simulation', nullable=False))
    op.create_index(op.f('ix_devices_device_family'), 'devices', ['device_family'], unique=False)
    op.create_index('ix_devices_family', 'devices', ['device_family'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_devices_family', table_name='devices')
    op.drop_index(op.f('ix_devices_device_family'), table_name='devices')
    op.drop_column('devices', 'device_family')
    # ### end Alembic commands ###