"""devices

Revision ID: 993e78ec5f36
Revises: 6b681a6aa7c6
Create Date: 2026-09-15 18:27:55.618032

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '993e78ec5f36'
down_revision: Union[str, Sequence[str], None] = '6b681a6aa7c6'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###