"""locations_and_zones

Revision ID: a32fa7a2f81c
Revises: 7c8b0c5db769
Create Date: 2026-09-29 18:53:25.213357

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'a32fa7a2f81c'
down_revision: Union[str, Sequence[str], None] = '7c8b0c5db769'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('locations',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('name', sa.String(length=128), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('zones',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('location_id', sa.UUID(), nullable=False),
    sa.Column('name', sa.String(length=128), nullable=False),
    sa.Column('moisture_threshold_low', sa.Numeric(precision=5, scale=4), nullable=False),
    sa.Column('moisture_threshold_high', sa.Numeric(precision=5, scale=4), nullable=False),
    sa.Column('schedule', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.ForeignKeyConstraint(['location_id'], ['locations.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_zones_location_id', 'zones', ['location_id'], unique=False)
    op.add_column('devices', sa.Column('zone_id', sa.UUID(), nullable=True))
    op.add_column('devices', sa.Column('location_id', sa.UUID(), nullable=True))
    op.drop_index(op.f('ix_devices_device_family'), table_name='devices')
    op.drop_index(op.f('ix_devices_family'), table_name='devices')
    op.drop_index(op.f('ix_devices_role'), table_name='devices')
    op.create_index(op.f('ix_devices_location_id'), 'devices', ['location_id'], unique=False)
    op.create_index(op.f('ix_devices_zone_id'), 'devices', ['zone_id'], unique=False)
    op.create_foreign_key(None, 'devices', 'locations', ['location_id'], ['id'], ondelete='SET NULL')
    op.create_foreign_key(None, 'devices', 'zones', ['zone_id'], ['id'], ondelete='SET NULL')
    op.drop_column('devices', 'created_at')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('devices', sa.Column('created_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), autoincrement=False, nullable=False))
    # WARNING: constraint name is None; this directive will fail as
    # rendered.  Add a name, or use a naming convention; see
    # https://alembic.sqlalchemy.org/en/latest/naming.html
    op.drop_constraint(None, 'devices', type_='foreignkey')
    # WARNING: constraint name is None; this directive will fail as
    # rendered.  Add a name, or use a naming convention; see
    # https://alembic.sqlalchemy.org/en/latest/naming.html
    op.drop_constraint(None, 'devices', type_='foreignkey')
    op.drop_index(op.f('ix_devices_zone_id'), table_name='devices')
    op.drop_index(op.f('ix_devices_location_id'), table_name='devices')
    op.create_index(op.f('ix_devices_role'), 'devices', ['role'], unique=False)
    op.create_index(op.f('ix_devices_family'), 'devices', ['device_family'], unique=False)
    op.create_index(op.f('ix_devices_device_family'), 'devices', ['device_family'], unique=False)
    op.drop_column('devices', 'location_id')
    op.drop_column('devices', 'zone_id')
    op.drop_index('ix_zones_location_id', table_name='zones')
    op.drop_table('zones')
    op.drop_table('locations')
    # ### end Alembic commands ###