"""sensor_readings

Revision ID: bedcddf8094f
Revises: a32fa7a2f81c
Create Date: 2026-10-06 14:30:37.355120

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'bedcddf8094f'
down_revision: Union[str, Sequence[str], None] = 'a32fa7a2f81c'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('sensor_readings',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('device_id', sa.UUID(), nullable=False),
    sa.Column('value', sa.Numeric(precision=10, scale=4), nullable=False),
    sa.Column('unit', sa.String(length=32), nullable=False),
    sa.Column('source', sa.String(length=32), nullable=False),
    sa.Column('recorded_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['device_id'], ['devices.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_sensor_readings_device_id'), 'sensor_readings', ['device_id'], unique=False)
    op.create_index('ix_sensor_readings_device_recorded_at', 'sensor_readings', ['device_id', sa.literal_column('recorded_at DESC')], unique=False)
    op.add_column('devices', sa.Column('sampling_interval_seconds', sa.Integer(), server_default='300', nullable=False))
    op.add_column('devices', sa.Column('tracking_enabled', sa.Boolean(), server_default='true', nullable=False))
    op.drop_index(op.f('ix_devices_zone_id'), table_name='devices')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index(op.f('ix_devices_zone_id'), 'devices', ['zone_id'], unique=False)
    op.drop_column('devices', 'tracking_enabled')
    op.drop_column('devices', 'sampling_interval_seconds')
    op.drop_index('ix_sensor_readings_device_recorded_at', table_name='sensor_readings')
    op.drop_index(op.f('ix_sensor_readings_device_id'), table_name='sensor_readings')
    op.drop_table('sensor_readings')
    # ### end Alembic commands ###